name: Run bots

on:
  workflow_dispatch:
  push:
    paths: "user_interface.py"

jobs:
  run-bot1nokk:
    concurrency:
      group: bot1nokk
      cancel-in-progress: false
    name: Run bot1nokk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Token
        run: sed -i "s/litoken_idk/${{ secrets.TOKEN4 }}/g" config.yml

      - name: get sf
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar
          rm stockfish-*.tar
          mv -f stockfish/stockfish-* engines/stockfish
          rm -r stockfish
        
      - name: chmod
        run: chmod +x ./engines/stockfish ./engines/fairysf
        
      - name: Run bot
        run: |
          python -u user_interface.py "matchmaking" "join lichess-racing-kings" &
          PID=$!
          # abc
          ( sleep 20100 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: Self-restart
        if: always()
        run: gh workflow run run-all.yml
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          
  run-sfbot1nok:
    concurrency:
      group: sf_bot1nok
      cancel-in-progress: false
    name: Run sf bot1nok
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Token
        run: sed -i "s/litoken_idk/${{ secrets.TOKEN }}/g" config.yml

      - name: get sf
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar
          rm stockfish-*.tar
          mv -f stockfish/stockfish-* engines/stockfish
          rm -r stockfish
        
      - name: chmod
        run: chmod +x ./engines/stockfish ./engines/fairysf
        
      - name: Run bot
        run: |
          python -u user_interface.py "matchmaking" "join lichess-racing-kings" &
          PID=$!
          # abc
          ( sleep 20100 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: Self-restart
        if: failure()
        run: gh workflow run run-all.yml
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  run-bot1e:
    concurrency:
      group: bot1e
      cancel-in-progress: false
    name: Run bot1e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install requirements
        uses: py-actions/py-dependency-install@v4.0.0
        
      - name: Token
        run: sed -i "s/litoken_idk/${{ secrets.TOKEN2 }}/g" config.yml

      - name: get sf
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar
          rm stockfish-*.tar
          mv -f stockfish/stockfish-* engines/stockfish
          rm -r stockfish
        
      - name: chmod
        run: chmod +x ./engines/stockfish ./engines/fairysf
        
      - name: Run bot
        run: |
          python -u user_interface.py "matchmaking" "join lichess-racing-kings" &
          PID=$!
          # abc
          ( sleep 20100 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: Self-restart
        if: failure()
        run: gh workflow run run-all.yml
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

  run-abdce:
    concurrency:
      group: abdce
      cancel-in-progress: false
    name: Run abdcebot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Token
        run: sed -i "s/litoken_idk/${{ secrets.TOKEN3 }}/g" config.yml

      - name: get sf
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar
          rm stockfish-*.tar
          mv -f stockfish/stockfish-* engines/stockfish
          rm -r stockfish
        
      - name: chmod
        run: chmod +x ./engines/stockfish ./engines/fairysf
        
      - name: Run bot
        run: |
          python user_interface.py "matchmaking" "join lichess-racing-kings" &
          PID=$!
          # abc
          ( sleep 20100 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: Self-restart
        if: failure()
        run: gh workflow run run-all.yml
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
